/**
 * RunSummaryGenerator — structured export for market/validation teams.
 *
 * Converts raw run.eventLog and run.metrics into a clean, typed report.
 * Works headlessly (no DOM). Import and call generate(run) to get the summary.
 */

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const GENERATOR_VERSION = '1.0.0'
const OUTCOMES = ['breakthrough', 'partial', 'stalemate', 'collapse']

// ---------------------------------------------------------------------------
// Event type constants (mirrors engine logEvent calls)
// ---------------------------------------------------------------------------

const EVENT_TYPE = {
  RUN_STARTED: 'run_started',
  ENCOUNTER_STARTED: 'encounter_started',
  ENCOUNTER_RESULT: 'encounter_result',
  CARDS_DRAWN: 'cards_drawn',
  PLAYER_EFFECTS_RESOLVED: 'player_effects_resolved',
  OPPOSITION_RULE_TRIGGERED: 'opposition_rule_triggered',
  COLLAPSE_ARMED: 'collapse_armed',
  BREAKTHROUGH_UNLOCKED: 'breakthrough_unlocked',
  POOR_FIT_PLAY: 'play_validation_failed',
  PHASE_ENTERED: 'phase_entered',
  RUN_COMPLETED: 'run_completed',
  SAVE_WRITTEN: 'save_written',
  SAVE_LOADED: 'save_loaded',
}

// ---------------------------------------------------------------------------
// Main generator
// ---------------------------------------------------------------------------

/**
 * Generate a structured summary from a run object.
 *
 * @param {object} run - The run object from GameEngine
 * @returns {RunSummary}
 */
export function generate(run) {
  if (!run) throw new Error('RunSummaryGenerator: run is required')

  const encounterResults = run.resultHistory || []
  const totalTurns = run.metrics?.turnsTaken ?? 0
  const poorFitPlays = run.metrics?.poorFitPlays ?? 0

  const resultDistribution = buildResultDistribution(encounterResults)
  const encounterMetrics = buildEncounterMetrics(encounterResults, totalTurns)
  const cardMetrics = buildCardMetrics(run.eventLog, poorFitPlays)
  const eventLogSummary = buildEventLogSummary(run.eventLog)
  const duration = buildDuration(run)

  return {
    runId: run.runId ?? null,
    seed: run.seed ?? null,
    status: run.status ?? 'unknown',

    resultDistribution,
    encounterMetrics,
    cardMetrics,
    eventLogSummary,
    duration,

    metadata: {
      schemaVersion: run.schemaVersion ?? 1,
      generatedAt: new Date().toISOString(),
      generatorVersion: GENERATOR_VERSION,
    },
  }
}

/**
 * Generate a markdown-formatted report for human readability.
 * Useful for pasting into Slack, Notion, etc.
 *
 * @param {object} run
 * @returns {string}
 */
export function generateMarkdown(run) {
  const summary = generate(run)
  const { resultDistribution, encounterMetrics, cardMetrics, eventLogSummary, duration } = summary

  const lines = [
    '# Run Summary',
    '',
    `**Run ID:** ${summary.runId}`,
    `**Seed:** ${summary.seed}`,
    `**Status:** ${summary.status}`,
    `**Duration:** ${duration.totalMs}ms (${duration.startedAt} → ${duration.completedAt})`,
    '',
    '## Result Distribution',
    '',
    ...OUTCOMES.map(
      (o) =>
        `  ${capitalize(o)}: ${resultDistribution[o]} (${pct(resultDistribution[o], resultDistribution.total)})`
    ),
    `  **Total: ${resultDistribution.total}**`,
    '',
    '## Encounter Metrics',
    '',
    `  Total Encounters: ${encounterMetrics.totalEncounters}`,
    `  Average Turns/Encounter: ${avg(encounterMetrics.averageTurnsPerEncounter)}`,
    '',
    '### Per-Encounter Breakdown',
    '',
    ...encounterMetrics.encounterResults.map(
      (e) => `  - ${e.name} (${e.encounterId}): ${capitalize(e.result)} — ${e.turns} turn${e.turns !== 1 ? 's' : ''}`
    ),
    '',
    '## Card Play Metrics',
    '',
    `  Total Plays: ${cardMetrics.totalPlays}`,
    `  Unique Cards Played: ${cardMetrics.uniqueCardsPlayed}`,
    `  Poor-Fit Play Rate: ${pct(cardMetrics.poorFitPlayRate)} (${cardMetrics.poorFitPlays}/${cardMetrics.totalPlays})`,
    '',
    '### Card Frequency',
    '',
    ...cardMetrics.cardPlayFrequency.map(
      ({ cardId, playCount }) => `  - ${cardId}: ${playCount} play${playCount !== 1 ? 's' : ''}`
    ),
    '',
    '## Event Log Summary',
    '',
    `  Total Events: ${eventLogSummary.totalEvents}`,
    `  Breakthrough Unlocks: ${eventLogSummary.breakthroughUnlocks}`,
    `  Collapse Arms: ${eventLogSummary.collapseArmed}`,
    `  Synergy Triggers: ${eventLogSummary.synergyTriggers}`,
    `  Risk Triggers: ${eventLogSummary.riskTriggers}`,
    '',
    `_Generated by RunSummaryGenerator v${GENERATOR_VERSION} at ${summary.metadata.generatedAt}_`,
  ]

  return lines.join('\n')
}

/**
 * Export summary as a JSON string.
 *
 * @param {object} run
 * @returns {string}
 */
export function generateJSON(run) {
  return JSON.stringify(generate(run), null, 2)
}

// ---------------------------------------------------------------------------
// Metric builders
// ---------------------------------------------------------------------------

function buildResultDistribution(encounterResults) {
  const dist = Object.fromEntries(OUTCOMES.map((o) => [o, 0]))
  for (const { result } of encounterResults) {
    if (dist.hasOwnProperty(result)) dist[result]++
  }
  dist.total = encounterResults.length
  return dist
}

function buildEncounterMetrics(encounterResults, totalTurns) {
  const total = encounterResults.length
  const avgTurns = total > 0 ? totalTurns / total : 0
  return {
    totalEncounters: total,
    averageTurnsPerEncounter: avgTurns,
    encounterResults: encounterResults.map((e) => ({
      encounterId: e.encounterId,
      name: e.name,
      result: e.result,
      turns: e.turn,
    })),
  }
}

function buildCardMetrics(eventLog, poorFitPlays) {
  const playEvents = filterByType(eventLog, EVENT_TYPE.PLAYER_EFFECTS_RESOLVED)
  const cardPlays = []

  for (const event of playEvents) {
    const { cards } = event.payload
    if (cards) cardPlays.push(...cards.filter(Boolean))
  }

  const totalPlays = cardPlays.length
  const uniqueCards = new Set(cardPlays)
  const cardPlayFrequency = buildCardFrequency(cardPlays)

  const totalPlayAttempts = totalPlays + poorFitPlays
  const poorFitPlayRate = totalPlayAttempts > 0 ? poorFitPlays / totalPlayAttempts : 0

  return {
    totalPlays,
    uniqueCardsPlayed: uniqueCards.size,
    cardPlayFrequency,
    poorFitPlays,
    poorFitPlayRate,
  }
}

function buildCardFrequency(cardPlays) {
  const counts = {}
  for (const cardId of cardPlays) {
    counts[cardId] = (counts[cardId] || 0) + 1
  }
  return Object.entries(counts)
    .map(([cardId, playCount]) => ({ cardId, playCount }))
    .sort((a, b) => b.playCount - a.playCount)
}

function buildEventLogSummary(eventLog) {
  const totalEvents = eventLog.length
  const eventsByType = {}

  let breakthroughUnlocks = 0
  let collapseArmed = 0
  let synergyTriggers = 0
  let riskTriggers = 0

  for (const event of eventLog) {
    const type = event.type
    eventsByType[type] = (eventsByType[type] || 0) + 1

    if (type === EVENT_TYPE.BREAKTHROUGH_UNLOCKED) breakthroughUnlocks++
    if (type === EVENT_TYPE.COLLAPSE_ARMED) collapseArmed++

    if (type === EVENT_TYPE.PLAYER_EFFECTS_RESOLVED) {
      const { synergy, risks } = event.payload
      if (synergy?.length) synergyTriggers += synergy.length
      if (risks?.length) riskTriggers += risks.length
    }
  }

  return {
    totalEvents,
    eventsByType,
    breakthroughUnlocks,
    collapseArmed,
    synergyTriggers,
    riskTriggers,
  }
}

function buildDuration(run) {
  const startedAt = run.createdAt ?? null
  const completedAt = run.updatedAt ?? null
  let totalMs = null
  if (startedAt && completedAt) {
    totalMs = new Date(completedAt) - new Date(startedAt)
  }
  return { startedAt, completedAt, totalMs }
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function filterByType(eventLog, type) {
  return eventLog.filter((e) => e.type === type)
}

function capitalize(str) {
  return str ? str[0].toUpperCase() + str.slice(1) : ''
}

function pct(value, total) {
  if (!total) return '0.0%'
  return `${((value / total) * 100).toFixed(1)}%`
}

function avg(value) {
  if (value === null || value === undefined) return '—'
  return typeof value === 'number' ? value.toFixed(2) : value
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export const RunSummaryGenerator = { generate, generateMarkdown, generateJSON }
export default RunSummaryGenerator
